### PR TITLE
Clip and Scripting Reference features

### PR DESCRIPTION
**Pull request by kryptot7**
Wick gotoAndLoop

* Added new function `Clip.gotoAndLoop`
````javascript
    /**
     * Repeats a specific part of the timeline.
     * @param {string|number} startFrame - A playhead position or name of a frame to start at.
     * @param {string|number} endFrame - When the playhead reaches this frame, it will loop back to startFrame.
     * @param {number|bool} [loop = true] - If true, will loop forever. If false, will play once and stop. If a number, it will play that many times in total.
     */
    gotoAndLoop (startFrame, endFrame, loop = true) {
        this.timeline.gotoAndLoop(startFrame, endFrame, loop);
    }
````
* Added support for playing Clips in reverse (Example: `gotoAndLoop(10, 1)`)
* **EDIT:** Note that all other `goto()` functions as well as `play()` and `stop()` will reset the Clip to its default behavior - play all frames forward and loop forever. I also considered simply adding the new functionality to play(), like below. That might be more intuitive, actually, so I'd be happy to change it. What do you think?
````javascript
play (startFrame = 1, endFrame = this.timeline.length, loop = true)
````
* Fixed bug: Clips playing out-of-range frames (they now bound given number between 1 and length)
* Fixed parent and this.parent not being equal in Wick code
   * Wick.Base.parent is now Wick.Base.parentBase to avoid confusion
* Added Clip.length and a few other flags to Clips
* Fixed script info typos
* Added build-engine.bat for Windows - double-click it in File Explorer to build engine
* Added js config file for Visual Studio Code

image
* Reference entries are now more informative and tell you what parameters are accepted
   * They also give you informative warnings
   * And cute emojis
* Added many helpful missing values to reference such as `identifier` and `parentClip`

**Example file**
[GotoAndLoop Test.zip](https://github.com/Wicklets/wick-editor/files/3419374/GotoAndLoop.Test.zip)

### CODE REVIEW

**Comment by zrispo** [comment]
Hey! I completely missed this PR for a very long time, really sorry!! 

These are all really nice features, again, really sorry I never saw this, I wish I could have looked this over and merged it all in way earlier.

I'm currently out of town but will be able to look through and get everything merged later this week. These should all be great new things to go along with the scripting update we're starting soon!

**Comment by kryptot7** [comment]
Awesome, thanks! 👍 😄 
Some of the conflicts listed below are probably because I renamed Wick.Base.parent to Wick.Base.parentBase, so resolving that shouldn't be too hard.

Also, after thinking about it a bit more, I have a few more notes on these changes:
* I think it would be much more intuitive to add arguments to play() rather than create an all new gotoAndLoop() function (as I discussed above).
* I noticed that functions in files like Clip.js are usually annotated with JSDoc style info above them, so for the reference, I found myself copying-and-pasting this information. Maybe at some point, the scripting reference could be auto-generated from this JSDoc information as part of the build process. That saves everyone from having to copy-and-paste internal code changes to scriptInfo.js.
* I don't think build-engine.bat is needed anymore because the functionality has since been added as an npm script, but I haven't tested that on my Windows machine.
* It would be good to add some common Javascript members to the reference as well, just so users know they are there. (For example, LocalStorage, Math.sin, Math.cos, etc.) Maybe even add a link to w3c or MDN tutorial pages on the topics.

I also think these Clip features could go hand in hand with the feature proposals I posted here:
https://forum.wickeditor.com/t/clip-api-ideas/1697/5?u=kryptot7
(This is a link to my newest post, since I revised some of my earlier ideas.)
Let me know what you think!

**Comment by kryptot7** [comment]
I found and fixed a bug in which parentFrame (which I added) is not equal to Clip.parentFrame. Sometimes it would refer to an internal frame, but now (I'm pretty sure) it always refers to the frame that owns the object. I also added another variable to the reference called thisFrame that can be used on a frame script to reference that specific frame.

I can't test these changes though. For some reason build-engine.bat used to work but now just gives me errors when I start Wick.

image

**Comment by Luxapodular** [comment]
While this has taken a while, we've just pushed a reference update to [WickEditor.com/#/learn](wickeditor.com/#/learn) which includes a number of the ideas from the PR! Thanks again @kryptot7 for providing this framework so long ago!

**Pull request closed without merging**
